// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4Mh55KEom5A9MfGIgPzxYCgTZLNQBup8',
    appId: '1:424379453738:web:11d9a4031a49732c910e53',
    messagingSenderId: '424379453738',
    projectId: 'facerecognition-cc926',
    authDomain: 'facerecognition-cc926.firebaseapp.com',
    storageBucket: 'facerecognition-cc926.appspot.com',
    measurementId: 'G-5KJ2TS45DM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh3ttokF7280H65DTA7_AWX6enVm1qrNU',
    appId: '1:424379453738:android:47a0fa8022f772e6910e53',
    messagingSenderId: '424379453738',
    projectId: 'facerecognition-cc926',
    storageBucket: 'facerecognition-cc926.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDdb6O68N-pa4Uyc6CUzsZRbHuttu04yE',
    appId: '1:424379453738:ios:100a7b22b8fe2f3a910e53',
    messagingSenderId: '424379453738',
    projectId: 'facerecognition-cc926',
    storageBucket: 'facerecognition-cc926.appspot.com',
    iosClientId: '424379453738-80329eufrqrtqr765a1i82fno8aguoen.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendancesystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDdb6O68N-pa4Uyc6CUzsZRbHuttu04yE',
    appId: '1:424379453738:ios:100a7b22b8fe2f3a910e53',
    messagingSenderId: '424379453738',
    projectId: 'facerecognition-cc926',
    storageBucket: 'facerecognition-cc926.appspot.com',
    iosClientId: '424379453738-80329eufrqrtqr765a1i82fno8aguoen.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendancesystem',
  );
}
